### ISSUE TITLE
Get-GitlabUser -All only retuns 20 users

### ISSUE THREAD

**Issue by planetscripton** [ngetchell/PSGitLab#148]
## 2. Describe Your Environment
Operating System and PowerShell version:
Windows, PowerShell Core 6.0.1

## 3. Expected Behavior
[comment] If you're describing a bug, tell us what should happen
[comment] If you're suggesting a change/improvement, tell us how it should work
Expect to receive all 46 users in our instance of Gitlab

## 4.Current Behavior
[comment] If describing a bug, tell us what happens instead of the expected behavior
[comment] If suggesting a change/improvement, explain the difference from current behavior
I only get 20 users back. It returns the same 20 users every time.

## 5. Possible Solution
[comment] Have a solution in mind?

## 6. Context
[Comment] How has this issue affected you? What are you trying to accomplish?
Unable to get a full list of users from the get-gitlabuser cmdlet.

**Comment by ngetchell** [comment]
Thanks for reporting. Must be a pagination bug. Will look into when I get a second.

**Comment by ngetchell** [comment]
Issue was at https://github.com/ngetchell/PSGitLab/blob/f866d1516ecdae85c8e3741150152e0061e86362/PSGitLab/Private/QueryGitLabAPI.ps1#L44

PowerShell Core returns the header as a string array and it is never properly casted to int. When it his the for loop it already satisfied the condition. 

The fix is simple. Call the first element of the array. If there is just a string it returns the correct int as well as if there is string[].

Look for the PR soon.
