### ISSUE TITLE
Using of Invoke-WebRequest uses Internet explorer engine

### ISSUE THREAD

**Issue by lw-schick** [ngetchell/PSGitLab#94]
The last days I run into a strange problem with a newly installed computer. Every time we wanted to run a command via this API returned in an error.

After some testing, we found out that the Internet Explorer was not started once. If this is the case, you get an error when you try to run `Invoke-WebReqeust`.

Invoke-WebRequest uses the internet explorer engine by default. We can avoid this by using the parameter `-UseBasicParsing`.

Here are some threads with similar problems:
* https://github.com/Dalmirog/OctoPosh/issues/144
* http://stackoverflow.com/questions/15211573/using-invoke-webrequest-in-powershell-3-0-spawns-a-windows-security-warning

I am not sure how we should solve this. I see the following possible solutions:
1. using the parameter `-UseBasicParsing`
2. probably using the function `Invoke-RestMethod`
3. using native dot net code

Option two seems to me the best one.

**Comment by ngetchell** [comment]
We use Invoke-WebRequest in two places and both for the same reason. We need more information than Invoke-RESTMethod gives us. Invoke-RESTMethod seems to be just 

``` powershell 
Invoke-WebRequest | Select -Expand Content
```

Sometimes we need the [HTTP status code](https://github.com/ngetchell/PSGitLab/blob/08573b2b841635f6b70bfefb98e0b1a8d0eac462/PSGitLab/Public/Configuration/Test-GitLabAPI.ps1#L8) or [a header to determine pagination](https://github.com/ngetchell/PSGitLab/blob/6183a16a8d667c7d90063296b9132ce11ff289fd/PSGitLab/Private/QueryGitLabAPI.ps1#L31). That information isn't displayed from Invoke-RestMethod. 

I think either option 1 or 3 since they meet all of our needs. Option 1 seems to be the easiest as all of our functions currently build parameters towards Invoke-WebRequest.  Going into .NET might require us to rewrite all of the API functions.
